export const categories = [
    "Networking",
    "Conferences",
    "Religion",
    "Arts and culture",
    "Music",
    "Seminars",
    "Comedy",
    "Sports",
    "Food and drink",
    "Charity and Fundraising",
    "Dinner and Award",
    "Party",
    // "General",
]