export const categories = [
    "General",
    "Music Concerts",
    "Art Exhibitions",
    "Tech Conferences",
    "Fitness Classes",
    "Food Festivals",
    "Cooking Workshops",
    "Comedy Shows",
    "Networking Events",
    "Educational Workshops",
    "Sports Tournaments",
    "Fashion Shows",
    "Charity Fundraisers",
    "Outdoor Adventures",
    "Gaming Tournaments",
    "Wellness Retreats",
    "Business Seminars",
    "Photography Exhibitions",
    "Cultural Festivals",
    "Science and Innovation Expos",
    "Book Launches",
    "Virtual Concerts",
]